server:
  url: "http://todo.lan"
  host: "0.0.0.0"
  port: 9991
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "19371937"
  dbname: "todo"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
jwt:
  accessSecret: "ceEHRwZM6Zrf02jQi2fSvULRAkSniZDUjOwyQVoRjIloPCarYb"
  refreshSecret: "zMNv582PjhZhQXIBpgRsaNjfGgpGfN430JaAO1MXpQJSOvHEUH"
  accessTTL: 1000h
  refreshTTL: 4320h # 6 month
smtp:
  host: "mail.dreamhost.com"
  port: 465
  from: "Todo"
  username: "noreplytodo@sns.ge"
  password: "c3nybeq2eLXx84ovGxnO05Xf"
