name: CI-Staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Node.js install
        uses: actions/setup-node@v1
        with:
          node-version: '18.0.0'

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install yarn
        run: |
          yarn install

      - name: Build services
        run: |
          DISABLE_ESLINT_PLUGIN=true yarn build

      - name: Get current datetime
        uses: 1466587594/get-current-time@v2
        id: current-datetime
        with:
          format: YYYYMMDDHHMMSS
          utcOffset: "+04:00"

      # Deploy to Staging Server
      - name: Staging Server - Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist"
          target: "/tmp/dist"
          strip_components: 1

      - name: Staging Server - Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /var/www/todo-frontend
            mv /tmp/dist /var/www/todo-frontend
            chown -R nginx:nginx /var/www/todo-frontend
            systemctl restart nginx
